name: boilerplate

packages:
    - apps/**
    # - features/**
    - "*"
scripts:
    test:selective_unit_test:
        run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
        description: Run Flutter tests for a specific package in this project.
        select-package:
            flutter: true
            dir-exists: test

    test:
        run: melos run test:selective_unit_test --no-select
        description: Run all Flutter tests in this project.
    
    web:
        run: melos exec -- flutter run lib/main.dart --debug
        select-package:
            scope: 'web'

    analyze:
        run: melos exec -- flutter analyze .
        description: Run `dart analyze` in all packages.

    gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh"

    postclean: >
        melos exec -- \
          rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./android/.idea ./.idea ./.dart-tool/build
