name: api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  args: ^2.0.0
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.4.1
  diacritic: ^0.1.3
  dotenv: ^4.0.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logging: ^1.0.2
  mime: ^1.0.1
  path: ^1.8.1
  shelf: ^1.1.0
  shelf_cors_headers: ^0.1.2
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0
  shelf_web_socket: ^1.0.1
  uuid: ^3.0.6
  web_socket_channel: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
  shelf_router_generator: ^1.0.2
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  freezed: ^1.1.1
